
- name: Stop old container
  # tags: [stop]
  shell: |
    docker rm -f demo-app || true

- name: Clean old images
  shell: |
    docker images \
      | grep "{{ repo_namespace }}/{{ repo_image }}" \
      | awk '{print $2}' \
      | xargs -r docker rmi 2>/dev/null || true

- name: Pull image
  shell: |
    docker pull {{ registry }}/{{ repo_namespace }}/{{ repo_image }}:{{ image_tag }}

- name: Run new container
  shell: |
    docker run -d \
      --name demo-app \
      --restart always \
      -p 8080:8080 \
      {{ registry }}/{{ repo_namespace }}/{{ repo_image }}:{{ image_tag }}
