- name: Stop old container
  # tags: [stop]
  ansible.builtin.shell: |
    docker rm -f {{ acr_image }} || true

- name: Clean old images
  ansible.builtin.shell: |
    docker images \
      | grep "{{ acr_namespace }}/{{ acr_image }}" \
      | awk '{print $2}' \
      | xargs -r docker rmi 2>/dev/null || true

- name: Pull image
  # tags: [pull]
  ansible.builtin.shell: |
    docker pull {{ registry }}/{{ acr_namespace }}/{{ acr_image }}:{{ acr_image_tag }}

- name: Run new container
  # tags: [start]
  ansible.builtin.shell: |
    docker run -d \
      --name {{ acr_image }} \
      --restart always \
      -p 8083:8083 \
      {{ registry }}/{{ acr_namespace }}/{{ acr_image }}:{{ acr_image_tag }}
