name: Ansible CI/CD

on:
  push:
    branches: [main, feature_*]
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      cloud_type:
        description: aws or alicloud
        type: string
      host_ips:
        description: target host ips, comma-separated string (e.g. "10.0.1.1,10.0.1.2")
        type: string
      trigger-event:
        type: string
      DEPLOY_ENV:
        type: string
        default: 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible ansible-lint

      - name: Syntax check
        run: ansible-playbook -i github-actions-demo/inventory.ini github-actions-demo/deploy.yml -e env=dev --syntax-check

      - name: ansible-lint
        run: ansible-lint roles/acr/tasks/main.yml roles/deploy/tasks/main.yml

  ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get ECS IP or Fallback
        if: ${{ github.event_name == 'workflow_call' }}
        run: |
          if [ -n ${{ inputs.host_ips }} ]; then
            echo "[${{ inputs.DEPLOY_ENV }}]" > /tmp/inventory.ini
            echo ${{ inputs.host_ips }} | tr ',' '\n' >> /tmp/inventory.ini
            echo "Using terraform IPs: $(cat /tmp/inventory.ini)"
          fi

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      
